### ISSUE TITLE
Add a possibility to change a color of a main message in addition to attachment color

### ISSUE THREAD

**Issue by fabasoad** [cemkiy/action-slacker#4]
**Description:**
Is there any chance to change the main color of a message? Would be great to have such possibility as default grey color looks a bit confusing. Thanks.

**Screenshot:**
![1](https://user-images.githubusercontent.com/2127723/70318189-d190a280-1862-11ea-88c8-b558b9c0b2ae.png)

**Comment by cemkiy** [comment]
No chance. But all attachments will be same color to next version. It seems ugly. You are right. Thanks your advice ;)

**Comment by fabasoad** [comment]
Got it. Thanks for reply :) You can close this ticket.

**Comment by cemkiy** [comment]
updated with this [commit](https://github.com/cemkiy/action-slacker/commit/29793fe3e716cca9e68381ffd0de0c2271a05d37). :tada:
