### ISSUE TITLE
GitHub Actions deprecation may affect this action

### ISSUE THREAD

**Issue by emmasax4** [cemkiy/action-slacker#9]
Hello @cemkiy,

GitHub announced a new deprecation recently, described [here](https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/). They want GitHub Action authors to update any usage of `@actions/core` to be `v1.2.6` or higher to receive new `addPath` and `exportVariable` functions. I see [this line](https://github.com/cemkiy/action-slacker/blob/master/package.json#L24) in the `package.json`, which indicates to me that this action will most likely need to be updated to use a more recent version of `@actions/core`. Can you verify if this is true, and if it is, make the appropriate changes to avoid this deprecation?

Thank you in advance.

Emma

**Comment by emmasax4** [comment]
Actually it looks like https://github.com/cemkiy/action-slacker/pull/8 perfectly represents what changes would need to be made to update this.

**Comment by emmasax4** [comment]
I'm closing this issue because I'd like to clean up my Open Issues list. In order to resolve the issue on my end, I ended up applying those required changes to [my fork of this project](https://github.com/emmasax4/slack-notifier-action), which has fixed the deprecation for myself.

I still think this would be a valuable fix for all users of this action, but I have no more concerns for myself specifically.

Feel free to reopen this issue if it's needed further down the line.

**Comment by cemkiy** [comment]
merge is done. sorry for delay ;)

**Comment by emmasax4** [comment]
@cemkiy That's okay. Thank you for swift action once you saw this!
